[2023-06-16T07:14:44.555+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:47:07.980597+00:00 [queued]>
[2023-06-16T07:14:44.563+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:47:07.980597+00:00 [queued]>
[2023-06-16T07:14:44.563+0200] {taskinstance.py:1308} INFO - Starting attempt 35 of 36
[2023-06-16T07:14:44.623+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_participants> on 2023-06-15 14:47:07.980597+00:00
[2023-06-16T07:14:44.629+0200] {standard_task_runner.py:57} INFO - Started process 271820 to run task
[2023-06-16T07:14:44.639+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ejecutar_python', 'check_participants', 'manual__2023-06-15T14:47:07.980597+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmpu4zcqlhh']
[2023-06-16T07:14:44.642+0200] {standard_task_runner.py:85} INFO - Job 79: Subtask check_participants
[2023-06-16T07:14:45.820+0200] {task_command.py:410} INFO - Running <TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:47:07.980597+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-06-16T07:15:01.873+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ejecutar_python' AIRFLOW_CTX_TASK_ID='check_participants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T14:47:07.980597+00:00' AIRFLOW_CTX_TRY_NUMBER='35' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T14:47:07.980597+00:00'
[2023-06-16T07:15:01.883+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-16T07:15:01.883+0200] {logging_mixin.py:149} INFO - ['']
[2023-06-16T07:15:01.883+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - New participants found. Creating containers...
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - 0
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - <class 'int'>
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - prueba de lista ['hola_525']
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/host_2/1_6-6.mrxs']
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - container solito hola_525
[2023-06-16T07:15:01.884+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-16T07:15:01.885+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-16T07:15:01.885+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2
[2023-06-16T07:15:01.885+0200] {logging_mixin.py:149} INFO - nuevo /home/reynel1995/Thesis/hola_525
[2023-06-16T07:15:01.885+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/hola_525', '', '/home/reynel1995/Thesis/hola_525', '/home/reynel1995/Thesis/hola_525']
[2023-06-16T07:15:04.611+0200] {logging_mixin.py:149} INFO - Container hola_525 image built successfully.
[2023-06-16T07:15:07.906+0200] {logging_mixin.py:149} INFO - Container hola_525 started.
[2023-06-16T07:15:07.906+0200] {logging_mixin.py:149} INFO - copy files function ['/home/reynel1995/Thesis/hola_525', '', '/home/reynel1995/Thesis/hola_525', '/home/reynel1995/Thesis/hola_525']
[2023-06-16T07:15:07.906+0200] {logging_mixin.py:149} INFO - hola_525
[2023-06-16T07:15:08.308+0200] {logging_mixin.py:149} INFO - File /home/reynel1995/Thesis/host_1/Image_analysis.py copied to container hola_525 volume.
[2023-06-16T07:15:10.953+0200] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-06-16T07:15:10.957+0200] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 271820. PIDs of all processes in the group: [271820]
[2023-06-16T07:15:10.957+0200] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 271820
[2023-06-16T07:15:10.958+0200] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-16T07:15:10.996+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 308, in check_participants
    execute_command_in_containers("python /app/Image_analysis.py", index)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 221, in execute_command_in_containers
    response = container.exec_run(command)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/models/containers.py", line 199, in exec_run
    exec_output = self.client.api.exec_start(
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/api/exec_api.py", line 173, in exec_start
    output = self._read_from_socket(res, stream, tty=tty, demux=demux)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/api/client.py", line 429, in _read_from_socket
    return consume_socket_output(gen, demux=demux)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/socket.py", line 155, in consume_socket_output
    return bytes().join(frames)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/api/client.py", line 422, in <genexpr>
    gen = (data for (_, data) in gen)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/socket.py", line 112, in frames_iter_no_tty
    (stream, n) = next_frame_header(socket)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/socket.py", line 84, in next_frame_header
    data = read_exactly(socket, 8)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/socket.py", line 69, in read_exactly
    next_data = read(socket, n - len(data))
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/docker/utils/socket.py", line 40, in read
    poll.poll()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-06-16T07:15:11.013+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=ejecutar_python, task_id=check_participants, execution_date=20230615T144707, start_date=20230616T051444, end_date=20230616T051511
[2023-06-16T07:15:11.054+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task check_participants (Task received SIGTERM signal; 271820)
[2023-06-16T07:15:11.102+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=271820, status='terminated', exitcode=1, started='07:14:43') (271820) terminated with exit code 1
