[2023-07-07T12:15:53.897+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T12:15:53.922+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T12:15:53.923+0200] {taskinstance.py:1308} INFO - Starting attempt 10 of 10
[2023-07-07T12:15:53.984+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_command_in_containers> on 2023-07-05 03:56:32.740955+00:00
[2023-07-07T12:15:54.008+0200] {standard_task_runner.py:57} INFO - Started process 468631 to run task
[2023-07-07T12:15:54.014+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'execute_command_in_containers', 'manual__2023-07-05T03:56:32.740955+00:00', '--job-id', '671', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmpcqttlofb']
[2023-07-07T12:15:54.017+0200] {standard_task_runner.py:85} INFO - Job 671: Subtask execute_command_in_containers
[2023-07-07T12:15:54.149+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-07T12:15:54.357+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='execute_command_in_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T03:56:32.740955+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-05T03:56:32.740955+00:00'
[2023-07-07T12:15:56.998+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 254, in execute_command_in_containers
    data = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-07-07T12:15:57.009+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=execute_python, task_id=execute_command_in_containers, execution_date=20230705T035632, start_date=20230707T101553, end_date=20230707T101557
[2023-07-07T12:15:57.111+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 671 for task execute_command_in_containers (Expecting value: line 1 column 1 (char 0); 468631)
[2023-07-07T12:15:57.146+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T12:15:57.195+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
