[2023-07-07T14:17:51.677+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T14:17:51.684+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T14:17:51.685+0200] {taskinstance.py:1308} INFO - Starting attempt 20 of 20
[2023-07-07T14:17:51.701+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_command_in_containers> on 2023-07-05 03:56:32.740955+00:00
[2023-07-07T14:17:51.705+0200] {standard_task_runner.py:57} INFO - Started process 494884 to run task
[2023-07-07T14:17:51.707+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'execute_command_in_containers', 'manual__2023-07-05T03:56:32.740955+00:00', '--job-id', '751', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmprlcqvbn9']
[2023-07-07T14:17:51.709+0200] {standard_task_runner.py:85} INFO - Job 751: Subtask execute_command_in_containers
[2023-07-07T14:17:51.747+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-07T14:17:51.807+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='execute_command_in_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T03:56:32.740955+00:00' AIRFLOW_CTX_TRY_NUMBER='20' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-05T03:56:32.740955+00:00'
[2023-07-07T14:17:51.808+0200] {logging_mixin.py:149} INFO - python /app/classify_image.py
[2023-07-07T14:17:51.827+0200] {logging_mixin.py:149} INFO - <Container: c552592d1b14>
[2023-07-07T14:17:55.105+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 352, in execute_command_in_containers
    classify_image = data["classify_image"]
KeyError: 'classify_image'
[2023-07-07T14:17:55.112+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=execute_python, task_id=execute_command_in_containers, execution_date=20230705T035632, start_date=20230707T121751, end_date=20230707T121755
[2023-07-07T14:17:55.130+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 751 for task execute_command_in_containers ('classify_image'; 494884)
[2023-07-07T14:17:55.175+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T14:17:55.203+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
