[2023-07-07T12:26:48.921+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T12:26:48.930+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [queued]>
[2023-07-07T12:26:48.930+0200] {taskinstance.py:1308} INFO - Starting attempt 11 of 12
[2023-07-07T12:26:48.946+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_command_in_containers> on 2023-07-05 03:56:32.740955+00:00
[2023-07-07T12:26:48.951+0200] {standard_task_runner.py:57} INFO - Started process 470896 to run task
[2023-07-07T12:26:48.954+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'execute_command_in_containers', 'manual__2023-07-05T03:56:32.740955+00:00', '--job-id', '684', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmptoi6pmzp']
[2023-07-07T12:26:48.956+0200] {standard_task_runner.py:85} INFO - Job 684: Subtask execute_command_in_containers
[2023-07-07T12:26:49.017+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.execute_command_in_containers manual__2023-07-05T03:56:32.740955+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-07T12:26:49.110+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='execute_command_in_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-05T03:56:32.740955+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-05T03:56:32.740955+00:00'
[2023-07-07T12:26:49.714+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 255, in execute_command_in_containers
    data = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-07-07T12:26:49.721+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_python, task_id=execute_command_in_containers, execution_date=20230705T035632, start_date=20230707T102648, end_date=20230707T102649
[2023-07-07T12:26:49.743+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 684 for task execute_command_in_containers (Expecting value: line 1 column 1 (char 0); 470896)
[2023-07-07T12:26:49.772+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T12:26:49.807+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
