[2023-07-07T13:45:16.142+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T11:43:25.436870+00:00 [queued]>
[2023-07-07T13:45:16.150+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T11:43:25.436870+00:00 [queued]>
[2023-07-07T13:45:16.150+0200] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-07T13:45:16.186+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_command_in_containers> on 2023-07-07 11:43:25.436870+00:00
[2023-07-07T13:45:16.191+0200] {standard_task_runner.py:57} INFO - Started process 489316 to run task
[2023-07-07T13:45:16.194+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'execute_command_in_containers', 'manual__2023-07-07T11:43:25.436870+00:00', '--job-id', '736', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmpvsqljqtm']
[2023-07-07T13:45:16.195+0200] {standard_task_runner.py:85} INFO - Job 736: Subtask execute_command_in_containers
[2023-07-07T13:45:16.264+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T11:43:25.436870+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-07T13:45:16.357+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='execute_command_in_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T11:43:25.436870+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-07T11:43:25.436870+00:00'
[2023-07-07T13:45:16.359+0200] {logging_mixin.py:149} INFO - python /app/classify_image.py
[2023-07-07T13:45:16.379+0200] {logging_mixin.py:149} INFO - <Container: c552592d1b14>
[2023-07-07T13:45:19.883+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 257, in execute_command_in_containers
    data = json.loads(output)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
[2023-07-07T13:45:19.889+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=execute_python, task_id=execute_command_in_containers, execution_date=20230707T114325, start_date=20230707T114516, end_date=20230707T114519
[2023-07-07T13:45:19.906+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 736 for task execute_command_in_containers (Extra data: line 1 column 5 (char 4); 489316)
[2023-07-07T13:45:19.942+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T13:45:19.975+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
