[2023-07-04T14:26:57.821+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.is_processed manual__2023-07-04T12:25:08.154346+00:00 [queued]>
[2023-07-04T14:26:57.826+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.is_processed manual__2023-07-04T12:25:08.154346+00:00 [queued]>
[2023-07-04T14:26:57.827+0200] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-04T14:26:57.870+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): is_processed> on 2023-07-04 12:25:08.154346+00:00
[2023-07-04T14:26:57.873+0200] {standard_task_runner.py:57} INFO - Started process 8970 to run task
[2023-07-04T14:26:57.875+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'is_processed', 'manual__2023-07-04T12:25:08.154346+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmp51f4w2rd']
[2023-07-04T14:26:57.876+0200] {standard_task_runner.py:85} INFO - Job 437: Subtask is_processed
[2023-07-04T14:26:57.961+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.is_processed manual__2023-07-04T12:25:08.154346+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-04T14:26:58.080+0200] {abstractoperator.py:593} ERROR - Exception rendering Jinja template for task 'is_processed', field 'op_kwargs'. Template: {'username': '{{ ti.xcom_pull(task_ids="check_participants")[0][0] }}', 'process_selection': '{{ ti.xcom_pull(task_ids="check_participants")[0][1] }}'}
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 585, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: list object has no element 0
[2023-07-04T14:26:58.081+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 585, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 539, in _render
    return super()._render(template, context, dag=dag)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/jinja2/sandbox.py", line 303, in getitem
    return obj[argument]
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: list object has no element 0
[2023-07-04T14:26:58.088+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=execute_python, task_id=is_processed, execution_date=20230704T122508, start_date=20230704T122657, end_date=20230704T122658
[2023-07-04T14:26:58.159+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 437 for task is_processed (list object has no element 0; 8970)
[2023-07-04T14:26:58.169+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-04T14:26:58.204+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
