[2023-07-07T14:16:55.065+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T12:16:17.351991+00:00 [queued]>
[2023-07-07T14:16:55.073+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T12:16:17.351991+00:00 [queued]>
[2023-07-07T14:16:55.073+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-07T14:16:55.090+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): execute_command_in_containers> on 2023-07-07 12:16:17.351991+00:00
[2023-07-07T14:16:55.095+0200] {standard_task_runner.py:57} INFO - Started process 494675 to run task
[2023-07-07T14:16:55.098+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'execute_command_in_containers', 'manual__2023-07-07T12:16:17.351991+00:00', '--job-id', '750', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmp8s1g8q_a']
[2023-07-07T14:16:55.099+0200] {standard_task_runner.py:85} INFO - Job 750: Subtask execute_command_in_containers
[2023-07-07T14:16:55.142+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.execute_command_in_containers manual__2023-07-07T12:16:17.351991+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-07-07T14:16:55.226+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='execute_command_in_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-07-07T12:16:17.351991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-07T12:16:17.351991+00:00'
[2023-07-07T14:16:55.227+0200] {logging_mixin.py:149} INFO - python /app/classify_image.py
[2023-07-07T14:16:55.247+0200] {logging_mixin.py:149} INFO - <Container: c552592d1b14>
[2023-07-07T14:16:58.856+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 352, in execute_command_in_containers
    classify_image = data["classify_image"]
KeyError: 'classify_image'
[2023-07-07T14:16:58.862+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_python, task_id=execute_command_in_containers, execution_date=20230707T121617, start_date=20230707T121655, end_date=20230707T121658
[2023-07-07T14:16:58.882+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 750 for task execute_command_in_containers ('classify_image'; 494675)
[2023-07-07T14:16:58.926+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-07T14:16:58.970+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
