[2023-06-26T06:44:03.204+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [queued]>
[2023-06-26T06:44:03.212+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [queued]>
[2023-06-26T06:44:03.213+0200] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2023-06-26T06:44:03.234+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_participants> on 2023-06-26 04:30:13.590801+00:00
[2023-06-26T06:44:03.237+0200] {standard_task_runner.py:57} INFO - Started process 105236 to run task
[2023-06-26T06:44:03.240+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'check_participants', 'manual__2023-06-26T04:30:13.590801+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmpxsrw72qj']
[2023-06-26T06:44:03.242+0200] {standard_task_runner.py:85} INFO - Job 91: Subtask check_participants
[2023-06-26T06:44:03.290+0200] {task_command.py:410} INFO - Running <TaskInstance: execute_python.check_participants manual__2023-06-26T04:30:13.590801+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-06-26T06:44:03.346+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python' AIRFLOW_CTX_TASK_ID='check_participants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-26T04:30:13.590801+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-26T04:30:13.590801+00:00'
[2023-06-26T06:44:03.347+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - []
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - New participants found. Creating containers...
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - 0
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - <class 'int'>
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - ['reynel_95']
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - list test ['reynel_95']
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/Participant1/1_6-6.mrxs']
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - single container reynel_95
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1/1_6-6.mrxs
[2023-06-26T06:44:03.348+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1/1_6-6.mrxs
[2023-06-26T06:44:03.349+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/Participant1
[2023-06-26T06:44:03.349+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/Participant1/1_6-6.mrxs']
[2023-06-26T06:44:03.349+0200] {logging_mixin.py:149} INFO - id reynel_95
[2023-06-26T06:44:03.349+0200] {logging_mixin.py:149} INFO - folder_path /home/reynel1995/Thesis/Participant1/1_6-6.mrxs
[2023-06-26T06:44:06.813+0200] {logging_mixin.py:149} INFO - Container reynel_95 image built successfully.
[2023-06-26T06:44:09.121+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 267, in check_participants
    build_and_run_containers(index)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 125, in build_and_run_containers
    subprocess.run(run_command, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker run -d --name reynel_95 reynel_95' returned non-zero exit status 125.
[2023-06-26T06:44:09.127+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=execute_python, task_id=check_participants, execution_date=20230626T043013, start_date=20230626T044403, end_date=20230626T044409
[2023-06-26T06:44:09.145+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task check_participants (Command 'docker run -d --name reynel_95 reynel_95' returned non-zero exit status 125.; 105236)
[2023-06-26T06:44:09.152+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-26T06:44:09.186+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
