[2023-06-15T16:37:50.088+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ejecutar_python.check_participants scheduled__2023-06-09T22:00:00+00:00 [queued]>
[2023-06-15T16:37:50.099+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ejecutar_python.check_participants scheduled__2023-06-09T22:00:00+00:00 [queued]>
[2023-06-15T16:37:50.099+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T16:37:50.160+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_participants> on 2023-06-09 22:00:00+00:00
[2023-06-15T16:37:50.166+0200] {standard_task_runner.py:57} INFO - Started process 5094 to run task
[2023-06-15T16:37:50.171+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ejecutar_python', 'check_participants', 'scheduled__2023-06-09T22:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmp9rmjeer5']
[2023-06-15T16:37:50.174+0200] {standard_task_runner.py:85} INFO - Job 5: Subtask check_participants
[2023-06-15T16:37:50.294+0200] {task_command.py:410} INFO - Running <TaskInstance: ejecutar_python.check_participants scheduled__2023-06-09T22:00:00+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-06-15T16:37:50.485+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ejecutar_python' AIRFLOW_CTX_TASK_ID='check_participants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-09T22:00:00+00:00'
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - []
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - New participants found. Creating containers...
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - 0
[2023-06-15T16:37:50.487+0200] {logging_mixin.py:149} INFO - <class 'int'>
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - prueba de lista ['hola_525']
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/host_2/1_6-6.mrxs']
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - container solito hola_525
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2
[2023-06-15T16:37:50.488+0200] {logging_mixin.py:149} INFO - nuevo /home/reynel1995/Thesis/hola_525
[2023-06-15T16:37:50.489+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/hola_525']
[2023-06-15T16:39:23.752+0200] {logging_mixin.py:149} INFO - Container hola_525 image built successfully.
[2023-06-15T16:39:28.052+0200] {logging_mixin.py:149} INFO - Container hola_525 started.
[2023-06-15T16:39:28.053+0200] {logging_mixin.py:149} INFO - copy files function ['/home/reynel1995/Thesis/hola_525']
[2023-06-15T16:39:28.053+0200] {logging_mixin.py:149} INFO - hola_525
[2023-06-15T16:39:28.153+0200] {logging_mixin.py:149} INFO - File /home/reynel1995/Thesis/host_1/image_analysis.py copied to container hola_525 volume.
[2023-06-15T16:39:28.397+0200] {logging_mixin.py:149} INFO - Command 'python /app/image_analysis.py' executed in container hola_525. Output:
python: can't open file '/app/image_analysis.py': [Errno 2] No such file or directory
[2023-06-15T16:39:28.400+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 303, in check_participants
    execute_command_in_containers("python /app/image_analysis.py", index)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 230, in execute_command_in_containers
    for i, filename in enumerate(os.listdir(container_id)):
FileNotFoundError: [Errno 2] No such file or directory: 'hola_525'
[2023-06-15T16:39:28.409+0200] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=ejecutar_python, task_id=check_participants, execution_date=20230609T220000, start_date=20230615T143750, end_date=20230615T143928
[2023-06-15T16:39:28.460+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task check_participants ([Errno 2] No such file or directory: 'hola_525'; 5094)
[2023-06-15T16:39:28.477+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T16:39:28.513+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
