[2023-06-15T21:52:15.689+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:37:45.849041+00:00 [queued]>
[2023-06-15T21:52:15.694+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:37:45.849041+00:00 [queued]>
[2023-06-15T21:52:15.694+0200] {taskinstance.py:1308} INFO - Starting attempt 30 of 30
[2023-06-15T21:52:15.705+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_participants> on 2023-06-15 14:37:45.849041+00:00
[2023-06-15T21:52:15.708+0200] {standard_task_runner.py:57} INFO - Started process 93241 to run task
[2023-06-15T21:52:15.710+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ejecutar_python', 'check_participants', 'manual__2023-06-15T14:37:45.849041+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/thesis_container.py', '--cfg-path', '/tmp/tmptw49se2h']
[2023-06-15T21:52:15.712+0200] {standard_task_runner.py:85} INFO - Job 38: Subtask check_participants
[2023-06-15T21:52:15.752+0200] {task_command.py:410} INFO - Running <TaskInstance: ejecutar_python.check_participants manual__2023-06-15T14:37:45.849041+00:00 [running]> on host DESKTOP-3KJU1M7.
[2023-06-15T21:52:15.813+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ejecutar_python' AIRFLOW_CTX_TASK_ID='check_participants' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T14:37:45.849041+00:00' AIRFLOW_CTX_TRY_NUMBER='30' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T14:37:45.849041+00:00'
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - ['']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - New participants found. Creating containers...
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - 0
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - <class 'int'>
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - ['hola_525']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - prueba de lista ['hola_525']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/host_2/1_6-6.mrxs']
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - container solito hola_525
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-15T21:52:15.815+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2/1_6-6.mrxs
[2023-06-15T21:52:15.816+0200] {logging_mixin.py:149} INFO - /home/reynel1995/Thesis/host_2
[2023-06-15T21:52:15.816+0200] {logging_mixin.py:149} INFO - nuevo /home/reynel1995/Thesis/hola_525
[2023-06-15T21:52:15.816+0200] {logging_mixin.py:149} INFO - ['/home/reynel1995/Thesis/hola_525', '', '/home/reynel1995/Thesis/hola_525', '/home/reynel1995/Thesis/hola_525', '/home/reynel1995/Thesis/hola_525', '/home/reynel1995/Thesis/hola_525']
[2023-06-15T21:52:16.163+0200] {logging_mixin.py:149} INFO - Container hola_525 image built successfully.
[2023-06-15T21:52:16.244+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/reynel1995/thesis/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 323, in check_participants
    build_and_run_containers(index)
  File "/home/reynel1995/airflow/dags/thesis_container.py", line 145, in build_and_run_containers
    subprocess.run(run_command, shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker run -d --name hola_525 hola_525' returned non-zero exit status 125.
[2023-06-15T21:52:16.249+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ejecutar_python, task_id=check_participants, execution_date=20230615T143745, start_date=20230615T195215, end_date=20230615T195216
[2023-06-15T21:52:16.261+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task check_participants (Command 'docker run -d --name hola_525 hola_525' returned non-zero exit status 125.; 93241)
[2023-06-15T21:52:16.285+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T21:52:16.304+0200] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
